# Generated by Django 4.1.5 on 2023-01-12 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=200)),
                ('education', models.CharField(max_length=200)),
                ('hometown', models.CharField(max_length=200)),
            ],
        ),
    ]
