# Generated by Django 4.1.5 on 2023-01-12 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='songs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_type', models.CharField(max_length=200)),
                ('song_name', models.CharField(max_length=200)),
                ('singer_name', models.CharField(max_length=200)),
                ('music_director', models.CharField(max_length=200)),
            ],
        ),
    ]
